language: rust
rust:
- stable
- beta
- nightly
sudo: required
before_install:
- git clone https://github.com/tbuktu/libntru.git
- cd libntru && make && make install && cd ..
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_success: |
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/ntru_tests-* &&
  [ $TRAVIS_BRANCH = develop ] &&
  echo '<meta http-equiv=refresh content=0;url=ntru/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
