language: rust
rust:
- stable
- beta
- nightly
sudo: required
before_install:
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/k/kcov/kcov_25+dfsg-1ubuntu2_i386.deb
  - sudo dpkg -i kcov_25+dfsg-1ubuntu2_i386.deb
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_success: |
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/lib-* &&
  [ $TRAVIS_BRANCH = master ] &&
  echo '<meta http-equiv=refresh content=0;url=ntru/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
